name: phresident
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.5
  shared_preferences: ^2.2.2
  circle_nav_bar: ^2.0.1+1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  percent_indicator: ^4.2.3
  riverpod_annotation: ^2.3.2
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.8
  url_launcher: ^6.2.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/avatars/
    - assets/data/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
